# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
 branches:
   include:
     - Dev
 paths:
   include:
     - /WebAPI/**

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs:  
  - job: 'Build'
    displayName: 'Build job'
    pool:
      name: 'PTWebBuildMachines'

    variables:
      solution: '**/WebApps.sln'
      project: '**/WebAPI/WebAPI.csproj'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    
    - checkout: git://APS/aps-web@Dev
    - checkout: git://APS/aps-core@dev #used for common library references

    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '$(solution)'
        feedsToUse: 'config'
        #nugetConfigPath: ' D:\a\1\s\NuGet.config'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        vsVersion: '17.0'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true 
        /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(Build.ArtifactStagingDirectory)\WebApiApp.zip" 
        /p:DeployIisAppPath="Default Web Site"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        customVersion: '17.8'

# Apply migrations from the ReportsWebApp.DB project (NOT the prod migrations) to db in appsettings.json file. 
     # This is a useful step for our nightly builds, but shouldn't be copied to the production environment where we want direct control.
    #- script: dotnet ef database update --verbose --no-build --configuration Release --context CompanyDBContext --project $(Build.SourcesDirectory)/aps-api/PTIntegrationAPI/PTIntegrationAPI.csproj --startup-project $(Build.SourcesDirectory)/aps-api/PTIntegrationAPI/PTIntegrationAPI.csproj --connection "$(ConnectionString-WebApi-Dev)"
     # displayName: 'Run EF Core Migration'
      #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
      #continueOnError: true

     #Publish build results for use in the release pipelines
    - task: PublishBuildArtifacts@1
      inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: '76e01371-5a04-44df-b577-3affc90d9712'
        KeyVaultName: 'pt-webapp-vault-dev'
        SecretsFilter: '12-Dev-Inst1-Publish'
        RunAsPreJob: false
        
  #Publish to azure app service
- stage: 'PT_WebApp_Dev'
  displayName: 'Deploy the web application to Dev'
  jobs:
  - deployment: Deploy
    environment: PT-WebApp-Dev
  - job: 'Deploy_to_Dev'
    displayName: 'Deploy to Dev job'
    pool:
      name: 'PTWebBuildMachines'
      environment: PT-WebApp-Dev

    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
      System.Debug: 'true'
      ConnectionStrings.APICompanyDatabase: $(ConnectionString-WebApi-Dev)
      WebAppUrl: $(app-dev-webapp-url)

    steps:
    - download: current

    # File transform
    # Replace tokens with variable values in XML or JSON configuration files
    - task: FileTransform@1
      displayName: 'File transformation: appsettings.json'
      inputs:
        folderPath: '$(Pipeline.Workspace)/drop/*.zip'
        targetFiles: '**/appsettings.json' 
        fileType: json

    - task: AzureRmWebAppDeployment@4
      inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: '76e01371-5a04-44df-b577-3affc90d9712'
          appType: 'webApp'
          WebAppName: 'pt-api-dev'
          packageForLinux: '$(Pipeline.Workspace)/drop/WebApiApp.zip'


