using PT.APSCommon;

namespace PT.Transmissions.Forecast;

public class ForecastRequirement : IPTSerializable
{
    public readonly List<SchedulerDefinitions.InventoryKey> InventoryKeys;
    public readonly List<Tuple<DateTime, decimal>> ReqDateAndQties;

    public ForecastRequirement(IEnumerable<SchedulerDefinitions.InventoryKey> a_invKeys, IEnumerable<Tuple<DateTime, decimal>> a_requirements)
    {
        InventoryKeys = a_invKeys.ToList();
        ReqDateAndQties = a_requirements.ToList();
    }

    public ForecastRequirement(IReader a_reader)
    {
        InventoryKeys = new List<SchedulerDefinitions.InventoryKey>();
        ReqDateAndQties = new List<Tuple<DateTime, decimal>>();

        int count;
        DateTime date;
        decimal qty;

        a_reader.Read(out count);
        for (int i = 0; i < count; i++)
        {
            InventoryKeys.Add(new SchedulerDefinitions.InventoryKey(a_reader));
        }

        a_reader.Read(out count);
        for (int i = 0; i < count; i++)
        {
            a_reader.Read(out date);
            a_reader.Read(out qty);
            ReqDateAndQties.Add(new Tuple<DateTime, decimal>(date, qty));
        }
    }

    public int UniqueId => throw new NotImplementedException();

    public void Serialize(IWriter a_writer)
    {
        a_writer.Write(InventoryKeys.Count);
        foreach (SchedulerDefinitions.InventoryKey invKey in InventoryKeys)
        {
            invKey.Serialize(a_writer);
        }

        a_writer.Write(ReqDateAndQties.Count);
        foreach (Tuple<DateTime, decimal> req in ReqDateAndQties)
        {
            a_writer.Write(req.Item1);
            a_writer.Write(req.Item2);
        }
    }
}

public class ForecastShipmentGenerateT : ForecastBaseT, IPTSerializable
{
    public readonly ForecastRequirement Requirement;
    public readonly bool AutoGenerated;

    public ForecastShipmentGenerateT() { }

    public ForecastShipmentGenerateT(BaseId a_scenarioId, IEnumerable<SchedulerDefinitions.InventoryKey> a_invKeys, IEnumerable<Tuple<DateTime, decimal>> a_requirements, bool a_autoGenerated)
        : base(a_scenarioId)
    {
        Requirement = new ForecastRequirement(a_invKeys, a_requirements);
        AutoGenerated = a_autoGenerated;
    }

    public ForecastShipmentGenerateT(IReader a_reader)
        : base(a_reader)
    {
        Requirement = new ForecastRequirement(a_reader);
        a_reader.Read(out AutoGenerated);
    }

    public override void Serialize(IWriter a_writer)
    {
        base.Serialize(a_writer);
        Requirement.Serialize(a_writer);
        a_writer.Write(AutoGenerated);
    }

    public new static readonly int UNIQUE_ID = 809;

    public override int UniqueId => UNIQUE_ID;

    public override string Description => "Forecast generated";
}

public class MultiForecastShipmentGenerateT : ForecastBaseT, IPTSerializable
{
    public readonly List<ForecastRequirement> Requirements;
    public readonly bool AutoGenerated;

    public MultiForecastShipmentGenerateT() { }

    public MultiForecastShipmentGenerateT(BaseId a_scenarioId, List<ForecastRequirement> a_requirements, bool a_autoGenerated) : base(a_scenarioId)
    {
        Requirements = a_requirements;
        AutoGenerated = a_autoGenerated;
    }

    public MultiForecastShipmentGenerateT(IReader a_reader) : base(a_reader)
    {
        Requirements = new List<ForecastRequirement>();
        int c;
        a_reader.Read(out c);
        for (int i = 0; i < c; i++)
        {
            Requirements.Add(new ForecastRequirement(a_reader));
        }

        a_reader.Read(out AutoGenerated);
    }

    public override void Serialize(IWriter a_writer)
    {
        base.Serialize(a_writer);
        a_writer.Write(Requirements.Count);
        foreach (ForecastRequirement forecastGenT in Requirements)
        {
            forecastGenT.Serialize(a_writer);
        }

        a_writer.Write(AutoGenerated);
    }

    public new static readonly int UNIQUE_ID = 818;

    public override int UniqueId => UNIQUE_ID;

    public override string Description => "Forecasts generated";
}