// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI.Models.V1;

public partial class JobMaterialSupplyingActivity
{
    public DateTime? importDate { get; set; }

    public long? JobId { get; set; }

    public long? ManufacturingOrderId { get; set; }

    public long? OperationId { get; set; }

    public long? MaterialRequirementId { get; set; }

    public long? ActivityId { get; set; }

    public long? SupplyingJobId { get; set; }

    public long? SupplyingManufacturingOrderId { get; set; }

    public long? SupplyingOperationId { get; set; }

    public long SupplyingActivityId { get; set; }

    public double? SuppliedQty { get; set; }

    public int? SupplyBomLevel { get; set; }
}