// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI.Models.V1;

public partial class JobProductTransferOrderDemand
{
    public DateTime importDate { get; set; }

    public long JobProductId { get; set; }

    public long JobOperationId { get; set; }

    public long TransferOrderDistributionId { get; set; }

    public DateTime? RequiredDate { get; set; }

    public double? RequiredQty { get; set; }

    public string Notes { get; set; }
}