// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI.Models.V1;

public partial class KPI
{
    public DateTime importDate { get; set; }

    public string CalculatorName { get; set; }

    public double? CurrentValue { get; set; }

    public long CalculatorId { get; set; }
}