// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI.Models.V1;

public partial class ProductRule
{
    public DateTime importDate { get; set; }

    public long ItemId { get; set; }

    public long PlantId { get; set; }

    public long DepartmentId { get; set; }

    public long ResourceId { get; set; }

    public string OperationName { get; set; }

    public double? SetupHrs { get; set; }

    public bool? UseSetupHrs { get; set; }

    public double? CycleHrs { get; set; }

    public bool? UseCycleHrs { get; set; }

    public double? QtyPerCycle { get; set; }

    public bool? UseQtyPerCycle { get; set; }

    public double? MaterialPostProcessingHrs { get; set; }

    public bool? UseMaterialPostProcessingHrs { get; set; }

    public double? PostProcessingHrs { get; set; }

    public bool? UsePostProcessingHrs { get; set; }

    public double? PlanningScrapPercent { get; set; }

    public bool? UsePlanningScrapPercent { get; set; }

    public double? HeadStartHrs { get; set; }

    public bool? UseHeadStartHrs { get; set; }
}