// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI.Models.V1;

public partial class PurchasesToStock
{
    public DateTime importDate { get; set; }

    public long PurchaseToStockId { get; set; }

    public long? InventoryId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public long? ItemId { get; set; }

    public double? QtyOrdered { get; set; }

    public string ExternalId { get; set; }

    public DateTime? ScheduledReceiptDate { get; set; }

    public double? UnloadHrs { get; set; }

    public double? TransferHrs { get; set; }

    public DateTime? AvailableDate { get; set; }

    public string VendorExternalId { get; set; }

    public string BuyerExternalId { get; set; }

    public long? WarehouseId { get; set; }

    public DateTime? UnloadEndDate { get; set; }

    public string Notes { get; set; }

    public string AttributesSummary { get; set; }

    public bool? Firm { get; set; }

    public bool? Closed { get; set; }

    public double? DbrReceivingBufferHrs { get; set; }

    public DateTime? DbrReceiptDate { get; set; }

    public double? DbrCurrentPenetrationPercent { get; set; }

    public double? QtyReceived { get; set; }

    public string MaintenanceMethod { get; set; }
}