// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI.Models.V1;

public partial class Warehouse
{
    public string ExternalId { get; set; }

    public string Name { get; set; }

    public string PlantExternalId { get; set; }
}